server:
  port: 8030

spring:
  application:
    name: service-qr
    zipkin:
      base-url: http://localhost:9411/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/qr-codes
    username: qr-code-username
    password: qr-code-password
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  file:
    name: logs\service-qr.log
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

kafka:
  address: http://localhost:9093
  topic:
    qr: qr_code
  group_id:
    qr: qr_group_id