server:
  port: 8020

spring:
  application:
    name: service-person
  zipkin:
    base-url: http://localhost:9411/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/people
    username: person
    password: person-password
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  file:
    name: logs\application-debug.log
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE